version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: xfdashboard-db
    environment:
      MYSQL_ROOT_PASSWORD: Admin123.
      MYSQL_DATABASE: xf_dashboard
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./src/server
    container_name: xfdashboard-server
    environment:
      DATABASE_URL: "mysql://root:Admin123.@mysql:3306/xf_dashboard"
      PORT: 3006
      PUBLIC_IP: "0.0.0.0"
      JWT_SECRET: "dev-secret"
      ALLOW_DEV_HEADERS: 1
    ports:
      - "3006:3006"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  web:
    build:
      context: ./web
    container_name: xfdashboard-web
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3006"
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always

volumes:
  mysql_data:

