export type ThemeId = "default" | "analytics" | "orange-purple" | "dusty-blue" | "vibrant" | "charming-purple" | "white-grid" | "graphite" | "spruce" | "terracotta" | "nova" | "midnight" | "frost";

export type ThemeDefinition = {
  id: ThemeId;
  name: string;
  description: string;
  dashboardComponent: string;
  previewImage?: string;
  preview: {
    shell: string;
    surface: string;
    accent: string;
    darkPanel: string;
  };
  vars: Record<string, string>;
};

export const DEFAULT_THEME_ID: ThemeId = "default";

export const THEMES: Record<ThemeId, ThemeDefinition> = {
  default: {
    id: "default",
    name: "默认主题",
    description: "冷白与蓝绿色点缀的现代工作台，清爽且更轻盈。",
    dashboardComponent: "DefaultDashboard",
    previewImage: "/themes/packages/DefaultDashboard.png",
    preview: {
      shell: "linear-gradient(180deg,#f7f8fa 0%,#eef2f4 100%)",
      surface: "#ffffff",
      accent: "#168f9c",
      darkPanel: "#1f4d57",
    },
    vars: {
      "theme-app-bg": "linear-gradient(180deg,#f7f8fa 0%,#eef2f4 100%)",
      "theme-shell-bg": "#f4f6f8",
      "theme-shell-border": "#e3e8ed",
      "theme-shell-shadow": "0 16px 36px rgba(15,23,42,0.04)",
      "theme-header-bg": "rgba(255,255,255,0.9)",
      "theme-header-border": "#dbe4ea",
      "theme-header-shadow": "0 1px 0 rgba(15,23,42,0.04)",
      "theme-sidebar-bg": "#ffffff",
      "theme-sidebar-border": "#edf1f5",
      "theme-sidebar-text": "#4d5b66",
      "theme-sidebar-muted": "#97a6b2",
      "theme-sidebar-hover-bg": "#f3f7f8",
      "theme-sidebar-hover-text": "#18222d",
      "theme-sidebar-active-bg": "#e7f6f3",
      "theme-sidebar-active-text": "#167c74",
      "theme-sidebar-icon-bg": "#f2f5f7",
      "theme-sidebar-icon-text": "#7f8f99",
      "theme-sidebar-icon-active-bg": "#ffffff",
      "theme-sidebar-icon-active-text": "#167c74",
      "theme-surface-bg": "#ffffff",
      "theme-surface-border": "#e4eaef",
      "theme-surface-shadow": "0 10px 28px rgba(15,23,42,0.04)",
      "theme-hero-bg": "linear-gradient(180deg,#ffffff 0%,#f5fbfa 100%)",
      "theme-hero-border": "#e1eceb",
      "theme-hero-shadow": "0 14px 34px rgba(16,93,104,0.05)",
      "theme-dark-panel-bg": "#1f4d57",
      "theme-dark-panel-border": "rgba(31,77,87,0.08)",
      "theme-dark-panel-shadow": "0 18px 40px rgba(31,77,87,0.16)",
      "theme-metric-bg": "#f8fbfb",
      "theme-metric-border": "#e4eef0",
      "theme-metric-shadow": "none",
      "theme-label-text": "#42505a",
      "theme-hint-text": "#99a7b2",
      "theme-body-text": "#18222d",
      "theme-muted-text": "#6f7f8c",
      "theme-dialog-section-bg": "#f4f7f8",
      "theme-empty-icon-bg": "#edf5f4",
      "theme-empty-icon-text": "#78949a",
      "theme-input-bg": "#ffffff",
      "theme-input-border": "#d8e2e8",
    },
  },
  analytics: {
    id: "analytics",
    name: "高级分析",
    description: "温馨柔和的圆角网格风，强调丰富多彩的图表模块。",
    dashboardComponent: "AnalyticsDashboard",
    previewImage: "/themes/packages/AnalyticsDashboard.png",
    preview: {
      shell: "#F4EFEA",
      surface: "#ffffff",
      accent: "#2E62A6",
      darkPanel: "#2A4B82",
    },
    vars: {
      "theme-app-bg": "#F4EFEA",
      "theme-shell-bg": "#F4EFEA",
      "theme-shell-border": "transparent",
      "theme-shell-shadow": "none",
      "theme-header-bg": "#F4EFEA",
      "theme-header-border": "transparent",
      "theme-header-shadow": "none",
      "theme-sidebar-bg": "#F4EFEA",
      "theme-sidebar-border": "transparent",
      "theme-sidebar-text": "#4b5563",
      "theme-sidebar-muted": "#9ca3af",
      "theme-sidebar-hover-bg": "#EFE6DF",
      "theme-sidebar-hover-text": "#111827",
      "theme-sidebar-active-bg": "#2E62A6",
      "theme-sidebar-active-text": "#ffffff",
      "theme-sidebar-icon-bg": "#EFE6DF",
      "theme-sidebar-icon-text": "#6b7280",
      "theme-sidebar-icon-active-bg": "transparent",
      "theme-sidebar-icon-active-text": "#ffffff",
      "theme-surface-bg": "#ffffff",
      "theme-surface-border": "transparent",
      "theme-surface-shadow": "0 4px 24px rgba(0,0,0,0.02)",
      "theme-hero-bg": "#2E62A6",
      "theme-hero-border": "transparent",
      "theme-hero-shadow": "0 8px 30px rgba(0,0,0,0.05)",
      "theme-dark-panel-bg": "#2E62A6",
      "theme-dark-panel-border": "transparent",
      "theme-dark-panel-shadow": "0 18px 40px rgba(46,98,166,0.16)",
      "theme-metric-bg": "#f8fbfb",
      "theme-metric-border": "transparent",
      "theme-metric-shadow": "none",
      "theme-label-text": "#4b5563",
      "theme-hint-text": "#9ca3af",
      "theme-body-text": "#111827",
      "theme-muted-text": "#6b7280",
      "theme-dialog-section-bg": "#f9fafb",
      "theme-empty-icon-bg": "#f3f4f6",
      "theme-empty-icon-text": "#9ca3af",
      "theme-input-bg": "#ffffff",
      "theme-input-border": "#d1d5db",
    },
  },
  "orange-purple": {
    id: "orange-purple",
    name: "橙紫主题",
    description: "活力橙与梦幻紫的撞色搭配，现代商业数据看板风格。",
    dashboardComponent: "OrangePurpleDashboard",
    previewImage: "/themes/packages/OrangePurpleDashboard.png",
    preview: {
      shell: "#F7F8FC",
      surface: "#ffffff",
      accent: "#FF6B35",
      darkPanel: "#7B61FF",
    },
    vars: {
      "theme-app-bg": "#F7F8FC",
      "theme-shell-bg": "#F7F8FC",
      "theme-shell-border": "transparent",
      "theme-shell-shadow": "none",
      "theme-header-bg": "#F7F8FC",
      "theme-header-border": "transparent",
      "theme-header-shadow": "none",
      "theme-sidebar-bg": "#ffffff",
      "theme-sidebar-border": "#f0f1f7",
      "theme-sidebar-text": "#4b5563",
      "theme-sidebar-muted": "#9ca3af",
      "theme-sidebar-hover-bg": "#f7f8fc",
      "theme-sidebar-hover-text": "#1a1d2e",
      "theme-sidebar-active-bg": "transparent",
      "theme-sidebar-active-text": "#FF6B35",
      "theme-sidebar-icon-bg": "#f7f8fc",
      "theme-sidebar-icon-text": "#9ca3af",
      "theme-sidebar-icon-active-bg": "transparent",
      "theme-sidebar-icon-active-text": "#FF6B35",
      "theme-surface-bg": "#ffffff",
      "theme-surface-border": "transparent",
      "theme-surface-shadow": "0 2px 12px rgba(0,0,0,0.06)",
      "theme-hero-bg": "linear-gradient(135deg,#FF8C5A 0%,#FF5533 100%)",
      "theme-hero-border": "transparent",
      "theme-hero-shadow": "0 8px 30px rgba(255,107,53,0.25)",
      "theme-dark-panel-bg": "linear-gradient(135deg,#9B7FFF 0%,#6B3FFF 100%)",
      "theme-dark-panel-border": "transparent",
      "theme-dark-panel-shadow": "0 8px 30px rgba(123,97,255,0.25)",
      "theme-metric-bg": "#f7f8fc",
      "theme-metric-border": "#ecedf5",
      "theme-metric-shadow": "none",
      "theme-label-text": "#8b92a9",
      "theme-hint-text": "#b0b8cc",
      "theme-body-text": "#1a1d2e",
      "theme-muted-text": "#8b92a9",
      "theme-dialog-section-bg": "#f7f8fc",
      "theme-empty-icon-bg": "#fff3ef",
      "theme-empty-icon-text": "#FF6B35",
      "theme-input-bg": "#ffffff",
      "theme-input-border": "#e8ebf4",
    },
  },
  "dusty-blue": {
    id: "dusty-blue",
    name: "蒙灰主题",
    description: "高级柔和的莫兰迪灰蓝调，带有微凸轻拟物阴影，宁静专注。",
    dashboardComponent: "DustyBlueDashboard",
    previewImage: "/themes/packages/DustyBlueDashboard.png",
    preview: {
      shell: "#F3F6F9",
      surface: "#ffffff",
      accent: "#4A5F7A",
      darkPanel: "#7D8C9F",
    },
    vars: {
      "theme-app-bg": "#F3F6F9",
      "theme-shell-bg": "#F3F6F9",
      "theme-shell-border": "transparent",
      "theme-shell-shadow": "none",
      "theme-header-bg": "linear-gradient(90deg, rgba(243,246,249,0.8) 0%, rgba(125,140,159,0.8) 100%)",
      "theme-header-border": "transparent",
      "theme-header-shadow": "none",
      "theme-sidebar-bg": "#F9FAFC",
      "theme-sidebar-border": "#E4E9F0",
      "theme-sidebar-text": "#7D8C9F",
      "theme-sidebar-muted": "#A2AFC1",
      "theme-sidebar-hover-bg": "#EEF1F5",
      "theme-sidebar-hover-text": "#4A5F7A",
      "theme-sidebar-active-bg": "#2E4156",
      "theme-sidebar-active-text": "#ffffff",
      "theme-sidebar-icon-bg": "#EEF1F5",
      "theme-sidebar-icon-text": "#7D8C9F",
      "theme-sidebar-icon-active-bg": "transparent",
      "theme-sidebar-icon-active-text": "#ffffff",
      "theme-surface-bg": "#ffffff",
      "theme-surface-border": "transparent",
      "theme-surface-shadow": "0 10px 40px rgba(125,140,159,0.12)",
      "theme-hero-bg": "#4A5F7A",
      "theme-hero-border": "transparent",
      "theme-hero-shadow": "0 10px 40px rgba(74,95,122,0.25)",
      "theme-dark-panel-bg": "#7D8C9F",
      "theme-dark-panel-border": "transparent",
      "theme-dark-panel-shadow": "0 10px 40px rgba(125,140,159,0.25)",
      "theme-metric-bg": "#F3F6F9",
      "theme-metric-border": "#E4E9F0",
      "theme-metric-shadow": "none",
      "theme-label-text": "#4A5F7A",
      "theme-hint-text": "#A2AFC1",
      "theme-body-text": "#2E4156",
      "theme-muted-text": "#7D8C9F",
      "theme-dialog-section-bg": "#F9FAFC",
      "theme-empty-icon-bg": "#E4E9F0",
      "theme-empty-icon-text": "#7D8C9F",
      "theme-input-bg": "#ffffff",
      "theme-input-border": "#E4E9F0",
    },
  },
  vibrant: {
    id: "vibrant",
    name: "活力主题",
    description: "极具年轻感的高饱和橙蓝对比配色，清晰利落的现代数据看板。",
    dashboardComponent: "VibrantDashboard",
    previewImage: "/themes/packages/VibrantDashboard.png",
    preview: {
      shell: "#F5F7FA",
      surface: "#ffffff",
      accent: "#0062FF",
      darkPanel: "#111827",
    },
    vars: {
      "theme-app-bg": "#F5F7FA",
      "theme-shell-bg": "#F5F7FA",
      "theme-shell-border": "transparent",
      "theme-shell-shadow": "none",
      "theme-header-bg": "rgba(245,247,250,0.8)",
      "theme-header-border": "transparent",
      "theme-header-shadow": "none",
      "theme-sidebar-bg": "#ffffff",
      "theme-sidebar-border": "#E5E7EB",
      "theme-sidebar-text": "#9CA3AF",
      "theme-sidebar-muted": "#D1D5DB",
      "theme-sidebar-hover-bg": "#F3F4F6",
      "theme-sidebar-hover-text": "#1F2937",
      "theme-sidebar-active-bg": "#0062FF",
      "theme-sidebar-active-text": "#ffffff",
      "theme-sidebar-icon-bg": "#F3F4F6",
      "theme-sidebar-icon-text": "#9CA3AF",
      "theme-sidebar-icon-active-bg": "transparent",
      "theme-sidebar-icon-active-text": "#ffffff",
      "theme-surface-bg": "#ffffff",
      "theme-surface-border": "transparent",
      "theme-surface-shadow": "0 8px 30px rgba(0,0,0,0.04)",
      "theme-hero-bg": "#0062FF",
      "theme-hero-border": "transparent",
      "theme-hero-shadow": "0 12px 32px rgba(0,98,255,0.25)",
      "theme-dark-panel-bg": "#111827",
      "theme-dark-panel-border": "transparent",
      "theme-dark-panel-shadow": "0 12px 32px rgba(17,24,39,0.25)",
      "theme-metric-bg": "#F9FAFB",
      "theme-metric-border": "#F3F4F6",
      "theme-metric-shadow": "none",
      "theme-label-text": "#374151",
      "theme-hint-text": "#9CA3AF",
      "theme-body-text": "#111827",
      "theme-muted-text": "#6B7280",
      "theme-dialog-section-bg": "#F9FAFB",
      "theme-empty-icon-bg": "#EFF6FF",
      "theme-empty-icon-text": "#0062FF",
      "theme-input-bg": "#ffffff",
      "theme-input-border": "#E5E7EB",
    },
  },
  "charming-purple": {
    id: "charming-purple",
    name: "魅紫主题",
    description: "温馨奶茶色大背景，搭配治愈系的魅紫、薄荷绿和深海蓝，柔软治愈。",
    dashboardComponent: "CharmingPurpleDashboard",
    previewImage: "/themes/packages/CharmingPurpleDashboard.png",
    preview: {
      shell: "#F5F0EB",
      surface: "#ffffff",
      accent: "#365CA8",
      darkPanel: "#B2A1D9",
    },
    vars: {
      "theme-app-bg": "#F5F0EB",
      "theme-shell-bg": "#F5F0EB",
      "theme-shell-border": "transparent",
      "theme-shell-shadow": "none",
      "theme-header-bg": "transparent",
      "theme-header-border": "transparent",
      "theme-header-shadow": "none",
      "theme-sidebar-bg": "#F5F0EB",
      "theme-sidebar-border": "transparent",
      "theme-sidebar-text": "#1A1D2E",
      "theme-sidebar-muted": "#8B92A9",
      "theme-sidebar-hover-bg": "rgba(255,255,255,0.5)",
      "theme-sidebar-hover-text": "#365CA8",
      "theme-sidebar-active-bg": "#365CA8",
      "theme-sidebar-active-text": "#ffffff",
      "theme-sidebar-icon-bg": "#ffffff",
      "theme-sidebar-icon-text": "#1A1D2E",
      "theme-sidebar-icon-active-bg": "transparent",
      "theme-sidebar-icon-active-text": "#ffffff",
      "theme-surface-bg": "#ffffff",
      "theme-surface-border": "transparent",
      "theme-surface-shadow": "0 8px 30px rgba(0,0,0,0.04)",
      "theme-hero-bg": "#365CA8",
      "theme-hero-border": "transparent",
      "theme-hero-shadow": "0 12px 32px rgba(54,92,168,0.25)",
      "theme-dark-panel-bg": "#B2A1D9",
      "theme-dark-panel-border": "transparent",
      "theme-dark-panel-shadow": "0 12px 32px rgba(178,161,217,0.25)",
      "theme-metric-bg": "#F5F0EB",
      "theme-metric-border": "transparent",
      "theme-metric-shadow": "none",
      "theme-label-text": "#1A1D2E",
      "theme-hint-text": "#8B92A9",
      "theme-body-text": "#1A1D2E",
      "theme-muted-text": "#8B92A9",
      "theme-dialog-section-bg": "#F5F0EB",
      "theme-empty-icon-bg": "#EFEAF4",
      "theme-empty-icon-text": "#B2A1D9",
      "theme-input-bg": "#ffffff",
      "theme-input-border": "#ffffff",
    },
  },
  "white-grid": {
    id: "white-grid",
    name: "白格栅主题",
    description: "高级轻拟物 Soft UI 风格，极简石板蓝配色与微凸柔和阴影。",
    dashboardComponent: "WhiteGridDashboard",
    previewImage: "/themes/packages/WhiteGridDashboard.png",
    preview: {
      shell: "#EBEFF3",
      surface: "#FFFFFF",
      accent: "#31465F",
      darkPanel: "#F2F4F7",
    },
    vars: {
      "theme-app-bg": "#EBEFF3",
      "theme-shell-bg": "#EBEFF3",
      "theme-shell-border": "transparent",
      "theme-shell-shadow": "none",
      "theme-header-bg": "transparent",
      "theme-header-border": "transparent",
      "theme-header-shadow": "none",
      "theme-sidebar-bg": "transparent",
      "theme-sidebar-border": "transparent",
      "theme-sidebar-text": "#8D98A9",
      "theme-sidebar-muted": "#B9C4D1",
      "theme-sidebar-hover-bg": "rgba(255,255,255,0.4)",
      "theme-sidebar-hover-text": "#31465F",
      "theme-sidebar-active-bg": "#31465F",
      "theme-sidebar-active-text": "#ffffff",
      "theme-sidebar-icon-bg": "#ffffff",
      "theme-sidebar-icon-text": "#8D98A9",
      "theme-sidebar-icon-active-bg": "transparent",
      "theme-sidebar-icon-active-text": "#ffffff",
      "theme-surface-bg": "#FFFFFF",
      "theme-surface-border": "#FFFFFF",
      "theme-surface-shadow": "0 8px 30px rgba(185,196,209,0.4)",
      "theme-hero-bg": "#31465F",
      "theme-hero-border": "transparent",
      "theme-hero-shadow": "0 12px 32px rgba(49,70,95,0.25)",
      "theme-dark-panel-bg": "#F2F4F7",
      "theme-dark-panel-border": "transparent",
      "theme-dark-panel-shadow": "none",
      "theme-metric-bg": "#FFFFFF",
      "theme-metric-border": "transparent",
      "theme-metric-shadow": "none",
      "theme-label-text": "#31465F",
      "theme-hint-text": "#8D98A9",
      "theme-body-text": "#232E3E",
      "theme-muted-text": "#8D98A9",
      "theme-dialog-section-bg": "#F9FAFB",
      "theme-empty-icon-bg": "#F2F4F7",
      "theme-empty-icon-text": "#31465F",
      "theme-input-bg": "#F2F4F7",
      "theme-input-border": "#F2F4F7",
    },
  },
  graphite: {
    id: "graphite",
    name: "石墨主题",
    description: "更克制的灰阶工作台，视觉更沉稳。",
    dashboardComponent: "GraphiteDashboard",
    previewImage: "/themes/packages/GraphiteDashboard.png",
    preview: {
      shell: "linear-gradient(180deg,#f3f4f6 0%,#e5e7eb 100%)",
      surface: "#ffffff",
      accent: "#0f172a",
      darkPanel: "#111827",
    },
    vars: {
      "theme-app-bg": "linear-gradient(180deg,#f3f4f6 0%,#eceff3 100%)",
      "theme-shell-bg": "#f6f7f8",
      "theme-shell-border": "#d7dbe2",
      "theme-shell-shadow": "0 16px 40px rgba(17,24,39,0.04)",
      "theme-header-bg": "#ffffff",
      "theme-header-border": "#d7dbe2",
      "theme-header-shadow": "0 1px 0 rgba(17,24,39,0.04)",
      "theme-sidebar-bg": "#f3f4f6",
      "theme-sidebar-border": "#d7dbe2",
      "theme-sidebar-text": "#4b5563",
      "theme-sidebar-muted": "#9ca3af",
      "theme-sidebar-hover-bg": "#eceff3",
      "theme-sidebar-hover-text": "#111827",
      "theme-sidebar-active-bg": "#e5e7eb",
      "theme-sidebar-active-text": "#111827",
      "theme-sidebar-icon-bg": "#e5e7eb",
      "theme-sidebar-icon-text": "#6b7280",
      "theme-sidebar-icon-active-bg": "#ffffff",
      "theme-sidebar-icon-active-text": "#111827",
      "theme-surface-bg": "#ffffff",
      "theme-surface-border": "#d7dbe2",
      "theme-surface-shadow": "0 8px 24px rgba(17,24,39,0.04)",
      "theme-hero-bg": "#ffffff",
      "theme-hero-border": "#d7dbe2",
      "theme-hero-shadow": "0 10px 30px rgba(17,24,39,0.05)",
      "theme-dark-panel-bg": "#111827",
      "theme-dark-panel-border": "rgba(17,24,39,0.08)",
      "theme-dark-panel-shadow": "0 18px 44px rgba(17,24,39,0.2)",
      "theme-metric-bg": "#f3f4f6",
      "theme-metric-border": "#dee2e8",
      "theme-metric-shadow": "none",
      "theme-label-text": "#374151",
      "theme-hint-text": "#6b7280",
      "theme-body-text": "#111827",
      "theme-muted-text": "#6b7280",
      "theme-dialog-section-bg": "#f3f4f6",
      "theme-empty-icon-bg": "#e5e7eb",
      "theme-empty-icon-text": "#9ca3af",
      "theme-input-bg": "#ffffff",
      "theme-input-border": "#d1d5db",
    },
  },
  spruce: {
    id: "spruce",
    name: "云杉主题",
    description: "带一点绿色气息的清爽工作台。",
    dashboardComponent: "SpruceDashboard",
    previewImage: "/themes/packages/SpruceDashboard.png",
    preview: {
      shell: "linear-gradient(180deg,#f4fbf8 0%,#e7f4ee 100%)",
      surface: "#ffffff",
      accent: "#0f766e",
      darkPanel: "#134e4a",
    },
    vars: {
      "theme-app-bg": "linear-gradient(180deg,#f4faf7 0%,#ecf5f0 100%)",
      "theme-shell-bg": "#f7fbf9",
      "theme-shell-border": "#d7e9e1",
      "theme-shell-shadow": "0 16px 40px rgba(19,78,74,0.04)",
      "theme-header-bg": "#ffffff",
      "theme-header-border": "#d7e9e1",
      "theme-header-shadow": "0 1px 0 rgba(19,78,74,0.04)",
      "theme-sidebar-bg": "#f3faf7",
      "theme-sidebar-border": "#d7e9e1",
      "theme-sidebar-text": "#0f766e",
      "theme-sidebar-muted": "#6b9f97",
      "theme-sidebar-hover-bg": "#e8f6ef",
      "theme-sidebar-hover-text": "#134e4a",
      "theme-sidebar-active-bg": "#d9f3e6",
      "theme-sidebar-active-text": "#115e59",
      "theme-sidebar-icon-bg": "#e4f7ee",
      "theme-sidebar-icon-text": "#0f766e",
      "theme-sidebar-icon-active-bg": "#ffffff",
      "theme-sidebar-icon-active-text": "#0f766e",
      "theme-surface-bg": "#ffffff",
      "theme-surface-border": "#d7e9e1",
      "theme-surface-shadow": "0 8px 24px rgba(19,78,74,0.04)",
      "theme-hero-bg": "#ffffff",
      "theme-hero-border": "#d7e9e1",
      "theme-hero-shadow": "0 10px 30px rgba(19,78,74,0.05)",
      "theme-dark-panel-bg": "#134e4a",
      "theme-dark-panel-border": "rgba(19,78,74,0.08)",
      "theme-dark-panel-shadow": "0 18px 44px rgba(19,78,74,0.2)",
      "theme-metric-bg": "#f4faf7",
      "theme-metric-border": "#dceee6",
      "theme-metric-shadow": "none",
      "theme-label-text": "#0f5952",
      "theme-hint-text": "#4a8b82",
      "theme-body-text": "#134e4a",
      "theme-muted-text": "#6b9f97",
      "theme-dialog-section-bg": "#eef8f3",
      "theme-empty-icon-bg": "#d1fae5",
      "theme-empty-icon-text": "#6ee7b7",
      "theme-input-bg": "#ffffff",
      "theme-input-border": "#b7d8cc",
    },
  },
  terracotta: {
    id: "terracotta",
    name: "赤陶主题",
    description: "温暖的陶土色工作台，适合想让财务界面更有气质的场景。",
    dashboardComponent: "TerracottaDashboard",
    previewImage: "/themes/packages/TerracottaDashboard.png",
    preview: {
      shell: "linear-gradient(180deg,#fff7f0 0%,#f6e7dc 100%)",
      surface: "#fffdf9",
      accent: "#c65d3a",
      darkPanel: "#6f2f1d",
    },
    vars: {
      "theme-app-bg": "linear-gradient(180deg,#fdf7f2 0%,#f4ebe3 100%)",
      "theme-shell-bg": "#fffaf6",
      "theme-shell-border": "#eadccf",
      "theme-shell-shadow": "0 16px 40px rgba(111,47,29,0.04)",
      "theme-header-bg": "#ffffff",
      "theme-header-border": "#eadccf",
      "theme-header-shadow": "0 1px 0 rgba(111,47,29,0.04)",
      "theme-sidebar-bg": "#fef7f1",
      "theme-sidebar-border": "#eadccf",
      "theme-sidebar-text": "#9a5b43",
      "theme-sidebar-muted": "#c08a72",
      "theme-sidebar-hover-bg": "#fbede3",
      "theme-sidebar-hover-text": "#7c3a20",
      "theme-sidebar-active-bg": "#fde2d2",
      "theme-sidebar-active-text": "#9f3415",
      "theme-sidebar-icon-bg": "#fbe9dd",
      "theme-sidebar-icon-text": "#b46949",
      "theme-sidebar-icon-active-bg": "#ffffff",
      "theme-sidebar-icon-active-text": "#c65d3a",
      "theme-surface-bg": "#fffdf9",
      "theme-surface-border": "#eadccf",
      "theme-surface-shadow": "0 8px 24px rgba(111,47,29,0.04)",
      "theme-hero-bg": "#fffdf9",
      "theme-hero-border": "#eadccf",
      "theme-hero-shadow": "0 10px 30px rgba(111,47,29,0.05)",
      "theme-dark-panel-bg": "#6f2f1d",
      "theme-dark-panel-border": "rgba(111,47,29,0.1)",
      "theme-dark-panel-shadow": "0 18px 44px rgba(111,47,29,0.2)",
      "theme-metric-bg": "#fff7f1",
      "theme-metric-border": "#efdfd2",
      "theme-metric-shadow": "none",
      "theme-label-text": "#7c3a20",
      "theme-hint-text": "#a0613f",
      "theme-body-text": "#6f2f1d",
      "theme-muted-text": "#c08a72",
      "theme-dialog-section-bg": "#fcf0e7",
      "theme-empty-icon-bg": "#fde8d8",
      "theme-empty-icon-text": "#f4a47c",
      "theme-input-bg": "#ffffff",
      "theme-input-border": "#d8baa7",
    },
  },
  nova: {
    id: "nova",
    name: "Nova",
    description: "深色宇宙毛玻璃工作台，强调沉浸感与大号数据排版。",
    dashboardComponent: "NovaDashboard",
    previewImage: "/themes/packages/NovaDashboard.png",
    preview: {
      shell: "radial-gradient(ellipse at 20% 50%, #0d1b3e 0%, #050b1a 60%, #000000 100%)",
      surface: "rgba(255,255,255,0.08)",
      accent: "#63b3ff",
      darkPanel: "rgba(0,0,0,0.52)",
    },
    vars: {
      "theme-app-bg": "radial-gradient(ellipse at 20% 50%, #0d1b3e 0%, #050b1a 60%, #000000 100%)",
      "theme-shell-bg": "rgba(255,255,255,0.03)",
      "theme-shell-border": "rgba(255,255,255,0.06)",
      "theme-shell-shadow": "0 24px 72px rgba(0,0,0,0.48)",
      "theme-header-bg": "rgba(5,11,26,0.72)",
      "theme-header-border": "rgba(255,255,255,0.08)",
      "theme-header-shadow": "0 0 0 1px rgba(255,255,255,0.05), 0 18px 40px rgba(0,0,0,0.38)",
      "theme-sidebar-bg": "rgba(5,11,26,0.85)",
      "theme-sidebar-border": "rgba(255,255,255,0.08)",
      "theme-sidebar-text": "#d5e3ff",
      "theme-sidebar-muted": "#6e84a8",
      "theme-sidebar-hover-bg": "rgba(255,255,255,0.06)",
      "theme-sidebar-hover-text": "#f0f4ff",
      "theme-sidebar-active-bg": "rgba(99,179,255,0.14)",
      "theme-sidebar-active-text": "#f0f4ff",
      "theme-sidebar-icon-bg": "rgba(255,255,255,0.04)",
      "theme-sidebar-icon-text": "#8ea6c8",
      "theme-sidebar-icon-active-bg": "rgba(99,179,255,0.16)",
      "theme-sidebar-icon-active-text": "#63b3ff",
      "theme-surface-bg": "rgba(255,255,255,0.05)",
      "theme-surface-border": "rgba(255,255,255,0.06)",
      "theme-surface-shadow": "0 0 0 1px rgba(255,255,255,0.06), 0 8px 32px rgba(0,0,0,0.45)",
      "theme-hero-bg": "rgba(255,255,255,0.06)",
      "theme-hero-border": "rgba(255,255,255,0.08)",
      "theme-hero-shadow": "0 0 0 1px rgba(255,255,255,0.08), 0 24px 64px rgba(0,0,0,0.5)",
      "theme-dark-panel-bg": "rgba(0,0,0,0.4)",
      "theme-dark-panel-border": "rgba(255,255,255,0.05)",
      "theme-dark-panel-shadow": "0 20px 48px rgba(0,0,0,0.45)",
      "theme-metric-bg": "rgba(255,255,255,0.07)",
      "theme-metric-border": "rgba(255,255,255,0.06)",
      "theme-metric-shadow": "0 0 0 1px rgba(255,255,255,0.06), 0 4px 16px rgba(0,0,0,0.3)",
      // semantic tokens
      "theme-label-text": "#a8b8d8",
      "theme-hint-text": "#354560",
      "theme-body-text": "#f0f4ff",
      "theme-muted-text": "#4a5f80",
      "theme-dialog-section-bg": "rgba(255,255,255,0.04)",
      "theme-empty-icon-bg": "rgba(99,179,255,0.1)",
      "theme-empty-icon-text": "#63b3ff",
      "theme-input-bg": "rgba(255,255,255,0.06)",
      "theme-input-border": "rgba(255,255,255,0.1)",
    },
  },
  midnight: {
    id: "midnight",
    name: "午夜主题",
    description: "深邃的深蓝暗色工作台，夜间使用护眼舒适。",
    dashboardComponent: "MidnightDashboard",
    previewImage: "/themes/packages/MidnightDashboard.png",
    preview: {
      shell: "linear-gradient(180deg,#0f172a 0%,#0c1424 100%)",
      surface: "#1e293b",
      accent: "#60a5fa",
      darkPanel: "#0f172a",
    },
    vars: {
      "theme-app-bg": "linear-gradient(180deg,#0f172a 0%,#0b1220 100%)",
      "theme-shell-bg": "#0f172a",
      "theme-shell-border": "#273449",
      "theme-shell-shadow": "none",
      "theme-header-bg": "#111827",
      "theme-header-border": "#273449",
      "theme-header-shadow": "0 1px 0 rgba(0,0,0,0.2)",
      "theme-sidebar-bg": "#0f172a",
      "theme-sidebar-border": "#273449",
      "theme-sidebar-text": "#94a3b8",
      "theme-sidebar-muted": "#475569",
      "theme-sidebar-hover-bg": "#172033",
      "theme-sidebar-hover-text": "#e2e8f0",
      "theme-sidebar-active-bg": "#172554",
      "theme-sidebar-active-text": "#93c5fd",
      "theme-sidebar-icon-bg": "#1e293b",
      "theme-sidebar-icon-text": "#64748b",
      "theme-sidebar-icon-active-bg": "#1e3a8a",
      "theme-sidebar-icon-active-text": "#60a5fa",
      "theme-surface-bg": "#1e293b",
      "theme-surface-border": "#334155",
      "theme-surface-shadow": "0 10px 30px rgba(2,6,23,0.28)",
      "theme-hero-bg": "#17212f",
      "theme-hero-border": "#334155",
      "theme-hero-shadow": "0 12px 32px rgba(2,6,23,0.3)",
      "theme-dark-panel-bg": "#020617",
      "theme-dark-panel-border": "rgba(2,6,23,0.12)",
      "theme-dark-panel-shadow": "0 16px 38px rgba(2,6,23,0.48)",
      "theme-metric-bg": "#162131",
      "theme-metric-border": "#314257",
      "theme-metric-shadow": "none",
      // semantic tokens
      "theme-label-text": "#cbd5e1",
      "theme-hint-text": "#64748b",
      "theme-body-text": "#f1f5f9",
      "theme-muted-text": "#64748b",
      "theme-dialog-section-bg": "#111827",
      "theme-empty-icon-bg": "#1e293b",
      "theme-empty-icon-text": "#334155",
      "theme-input-bg": "#0f172a",
      "theme-input-border": "#334155",
    },
  },
  frost: {
    id: "frost",
    name: "霜玻璃",
    description: "半透明毛玻璃层叠，冰蓝灰色调，轻盈现代。",
    dashboardComponent: "FrostDashboard",
    previewImage: "/themes/packages/FrostDashboard.png",
    preview: {
      shell: "radial-gradient(ellipse at 30% 20%, #ddeeff 0%, #e8f0f8 40%, #f0f4f8 100%)",
      surface: "rgba(255,255,255,0.72)",
      accent: "#2d7dd2",
      darkPanel: "rgba(20,50,90,0.85)",
    },
    vars: {
      "theme-app-bg": "radial-gradient(ellipse at 30% 20%, #ddeeff 0%, #e8f0f8 40%, #f0f4f8 100%)",
      "theme-shell-bg": "rgba(255,255,255,0.4)",
      "theme-shell-border": "rgba(255,255,255,0.6)",
      "theme-shell-shadow": "0 8px 32px rgba(100,140,180,0.08)",
      "theme-header-bg": "rgba(255,255,255,0.65)",
      "theme-header-border": "rgba(255,255,255,0.8)",
      "theme-header-shadow": "0 1px 0 rgba(100,140,180,0.1)",
      "theme-sidebar-bg": "rgba(255,255,255,0.55)",
      "theme-sidebar-border": "rgba(200,220,240,0.4)",
      "theme-sidebar-text": "#3d5a7a",
      "theme-sidebar-muted": "#7a9bb8",
      "theme-sidebar-hover-bg": "rgba(255,255,255,0.7)",
      "theme-sidebar-hover-text": "#1a3550",
      "theme-sidebar-active-bg": "rgba(255,255,255,0.9)",
      "theme-sidebar-active-text": "#1558a8",
      "theme-sidebar-icon-bg": "rgba(200,220,240,0.5)",
      "theme-sidebar-icon-text": "#5580a0",
      "theme-sidebar-icon-active-bg": "rgba(255,255,255,0.95)",
      "theme-sidebar-icon-active-text": "#1d6fd4",
      "theme-surface-bg": "rgba(255,255,255,0.72)",
      "theme-surface-border": "rgba(255,255,255,0.0)",
      "theme-surface-shadow": "0 4px 24px rgba(100,140,180,0.12), 0 1px 4px rgba(100,140,180,0.08)",
      "theme-hero-bg": "rgba(255,255,255,0.0)",
      "theme-hero-border": "rgba(255,255,255,0.0)",
      "theme-hero-shadow": "none",
      "theme-dark-panel-bg": "rgba(20,50,90,0.85)",
      "theme-dark-panel-border": "rgba(255,255,255,0.08)",
      "theme-dark-panel-shadow": "0 12px 40px rgba(20,50,90,0.2)",
      "theme-metric-bg": "rgba(255,255,255,0.75)",
      "theme-metric-border": "rgba(255,255,255,0.0)",
      "theme-metric-shadow": "0 2px 16px rgba(100,140,180,0.1), 0 1px 3px rgba(100,140,180,0.08)",
      "theme-label-text": "#2d4d6a",
      "theme-hint-text": "#8aadc8",
      "theme-body-text": "#1a3550",
      "theme-muted-text": "#6a8faa",
      "theme-dialog-section-bg": "rgba(240,246,252,0.8)",
      "theme-empty-icon-bg": "rgba(200,220,240,0.5)",
      "theme-empty-icon-text": "#7aaac8",
      "theme-input-bg": "rgba(255,255,255,0.8)",
      "theme-input-border": "rgba(180,210,235,0.6)",
    },
  },
};

export const THEME_LIST = Object.values(THEMES);
