export type ThemeId = "default" | "graphite" | "spruce" | "terracotta" | "midnight";

export type ThemeDefinition = {
  id: ThemeId;
  name: string;
  description: string;
  preview: {
    shell: string;
    surface: string;
    accent: string;
    darkPanel: string;
  };
  vars: Record<string, string>;
};

export const DEFAULT_THEME_ID: ThemeId = "default";

export const THEMES: Record<ThemeId, ThemeDefinition> = {
  default: {
    id: "default",
    name: "默认主题",
    description: "干净的白底工作台，适合长期使用。",
    preview: {
      shell: "linear-gradient(180deg,#f8fafc 0%,#eef2f7 100%)",
      surface: "#ffffff",
      accent: "#2563eb",
      darkPanel: "#0f172a",
    },
    vars: {
      "theme-app-bg": "linear-gradient(180deg,#f5f7fb 0%,#edf1f6 100%)",
      "theme-shell-bg": "#f8fafc",
      "theme-shell-border": "#d9e2ec",
      "theme-shell-shadow": "0 16px 40px rgba(15,23,42,0.04)",
      "theme-header-bg": "#ffffff",
      "theme-header-border": "#d9e2ec",
      "theme-header-shadow": "0 1px 0 rgba(15,23,42,0.04)",
      "theme-sidebar-bg": "#f7f9fc",
      "theme-sidebar-border": "#d9e2ec",
      "theme-sidebar-text": "#475569",
      "theme-sidebar-muted": "#94a3b8",
      "theme-sidebar-hover-bg": "#eef4fb",
      "theme-sidebar-hover-text": "#0f172a",
      "theme-sidebar-active-bg": "#dbeafe",
      "theme-sidebar-active-text": "#1d4ed8",
      "theme-sidebar-icon-bg": "#eaf0f6",
      "theme-sidebar-icon-text": "#64748b",
      "theme-sidebar-icon-active-bg": "#ffffff",
      "theme-sidebar-icon-active-text": "#2563eb",
      "theme-surface-bg": "#ffffff",
      "theme-surface-border": "#d9e2ec",
      "theme-surface-shadow": "0 8px 24px rgba(15,23,42,0.04)",
      "theme-hero-bg": "#ffffff",
      "theme-hero-border": "#d9e2ec",
      "theme-hero-shadow": "0 10px 30px rgba(15,23,42,0.05)",
      "theme-dark-panel-bg": "#0f172a",
      "theme-dark-panel-border": "rgba(15,23,42,0.08)",
      "theme-dark-panel-shadow": "0 18px 44px rgba(15,23,42,0.2)",
      "theme-metric-bg": "#f8fafc",
      "theme-metric-border": "#dde6ef",
      "theme-metric-shadow": "none",
      // semantic tokens
      "theme-label-text": "#374151",
      "theme-hint-text": "#6b7280",
      "theme-body-text": "#0f172a",
      "theme-muted-text": "#64748b",
      "theme-dialog-section-bg": "#f5f8fb",
      "theme-empty-icon-bg": "#f1f5f9",
      "theme-empty-icon-text": "#94a3b8",
      "theme-input-bg": "#ffffff",
      "theme-input-border": "#cbd5e1",
    },
  },
  graphite: {
    id: "graphite",
    name: "石墨主题",
    description: "更克制的灰阶工作台，视觉更沉稳。",
    preview: {
      shell: "linear-gradient(180deg,#f3f4f6 0%,#e5e7eb 100%)",
      surface: "#ffffff",
      accent: "#0f172a",
      darkPanel: "#111827",
    },
    vars: {
      "theme-app-bg": "linear-gradient(180deg,#f3f4f6 0%,#eceff3 100%)",
      "theme-shell-bg": "#f6f7f8",
      "theme-shell-border": "#d7dbe2",
      "theme-shell-shadow": "0 16px 40px rgba(17,24,39,0.04)",
      "theme-header-bg": "#ffffff",
      "theme-header-border": "#d7dbe2",
      "theme-header-shadow": "0 1px 0 rgba(17,24,39,0.04)",
      "theme-sidebar-bg": "#f3f4f6",
      "theme-sidebar-border": "#d7dbe2",
      "theme-sidebar-text": "#4b5563",
      "theme-sidebar-muted": "#9ca3af",
      "theme-sidebar-hover-bg": "#eceff3",
      "theme-sidebar-hover-text": "#111827",
      "theme-sidebar-active-bg": "#e5e7eb",
      "theme-sidebar-active-text": "#111827",
      "theme-sidebar-icon-bg": "#e5e7eb",
      "theme-sidebar-icon-text": "#6b7280",
      "theme-sidebar-icon-active-bg": "#ffffff",
      "theme-sidebar-icon-active-text": "#111827",
      "theme-surface-bg": "#ffffff",
      "theme-surface-border": "#d7dbe2",
      "theme-surface-shadow": "0 8px 24px rgba(17,24,39,0.04)",
      "theme-hero-bg": "#ffffff",
      "theme-hero-border": "#d7dbe2",
      "theme-hero-shadow": "0 10px 30px rgba(17,24,39,0.05)",
      "theme-dark-panel-bg": "#111827",
      "theme-dark-panel-border": "rgba(17,24,39,0.08)",
      "theme-dark-panel-shadow": "0 18px 44px rgba(17,24,39,0.2)",
      "theme-metric-bg": "#f3f4f6",
      "theme-metric-border": "#dee2e8",
      "theme-metric-shadow": "none",
      // semantic tokens
      "theme-label-text": "#374151",
      "theme-hint-text": "#6b7280",
      "theme-body-text": "#111827",
      "theme-muted-text": "#6b7280",
      "theme-dialog-section-bg": "#f3f4f6",
      "theme-empty-icon-bg": "#e5e7eb",
      "theme-empty-icon-text": "#9ca3af",
      "theme-input-bg": "#ffffff",
      "theme-input-border": "#d1d5db",
    },
  },
  spruce: {
    id: "spruce",
    name: "云杉主题",
    description: "带一点绿色气息的清爽工作台。",
    preview: {
      shell: "linear-gradient(180deg,#f4fbf8 0%,#e7f4ee 100%)",
      surface: "#ffffff",
      accent: "#0f766e",
      darkPanel: "#134e4a",
    },
    vars: {
      "theme-app-bg": "linear-gradient(180deg,#f4faf7 0%,#ecf5f0 100%)",
      "theme-shell-bg": "#f7fbf9",
      "theme-shell-border": "#d7e9e1",
      "theme-shell-shadow": "0 16px 40px rgba(19,78,74,0.04)",
      "theme-header-bg": "#ffffff",
      "theme-header-border": "#d7e9e1",
      "theme-header-shadow": "0 1px 0 rgba(19,78,74,0.04)",
      "theme-sidebar-bg": "#f3faf7",
      "theme-sidebar-border": "#d7e9e1",
      "theme-sidebar-text": "#0f766e",
      "theme-sidebar-muted": "#6b9f97",
      "theme-sidebar-hover-bg": "#e8f6ef",
      "theme-sidebar-hover-text": "#134e4a",
      "theme-sidebar-active-bg": "#d9f3e6",
      "theme-sidebar-active-text": "#115e59",
      "theme-sidebar-icon-bg": "#e4f7ee",
      "theme-sidebar-icon-text": "#0f766e",
      "theme-sidebar-icon-active-bg": "#ffffff",
      "theme-sidebar-icon-active-text": "#0f766e",
      "theme-surface-bg": "#ffffff",
      "theme-surface-border": "#d7e9e1",
      "theme-surface-shadow": "0 8px 24px rgba(19,78,74,0.04)",
      "theme-hero-bg": "#ffffff",
      "theme-hero-border": "#d7e9e1",
      "theme-hero-shadow": "0 10px 30px rgba(19,78,74,0.05)",
      "theme-dark-panel-bg": "#134e4a",
      "theme-dark-panel-border": "rgba(19,78,74,0.08)",
      "theme-dark-panel-shadow": "0 18px 44px rgba(19,78,74,0.2)",
      "theme-metric-bg": "#f4faf7",
      "theme-metric-border": "#dceee6",
      "theme-metric-shadow": "none",
      // semantic tokens
      "theme-label-text": "#0f5952",
      "theme-hint-text": "#4a8b82",
      "theme-body-text": "#134e4a",
      "theme-muted-text": "#6b9f97",
      "theme-dialog-section-bg": "#eef8f3",
      "theme-empty-icon-bg": "#d1fae5",
      "theme-empty-icon-text": "#6ee7b7",
      "theme-input-bg": "#ffffff",
      "theme-input-border": "#b7d8cc",
    },
  },
  terracotta: {
    id: "terracotta",
    name: "赤陶主题",
    description: "温暖的陶土色工作台，适合想让财务界面更有气质的场景。",
    preview: {
      shell: "linear-gradient(180deg,#fff7f0 0%,#f6e7dc 100%)",
      surface: "#fffdf9",
      accent: "#c65d3a",
      darkPanel: "#6f2f1d",
    },
    vars: {
      "theme-app-bg": "linear-gradient(180deg,#fdf7f2 0%,#f4ebe3 100%)",
      "theme-shell-bg": "#fffaf6",
      "theme-shell-border": "#eadccf",
      "theme-shell-shadow": "0 16px 40px rgba(111,47,29,0.04)",
      "theme-header-bg": "#ffffff",
      "theme-header-border": "#eadccf",
      "theme-header-shadow": "0 1px 0 rgba(111,47,29,0.04)",
      "theme-sidebar-bg": "#fef7f1",
      "theme-sidebar-border": "#eadccf",
      "theme-sidebar-text": "#9a5b43",
      "theme-sidebar-muted": "#c08a72",
      "theme-sidebar-hover-bg": "#fbede3",
      "theme-sidebar-hover-text": "#7c3a20",
      "theme-sidebar-active-bg": "#fde2d2",
      "theme-sidebar-active-text": "#9f3415",
      "theme-sidebar-icon-bg": "#fbe9dd",
      "theme-sidebar-icon-text": "#b46949",
      "theme-sidebar-icon-active-bg": "#ffffff",
      "theme-sidebar-icon-active-text": "#c65d3a",
      "theme-surface-bg": "#fffdf9",
      "theme-surface-border": "#eadccf",
      "theme-surface-shadow": "0 8px 24px rgba(111,47,29,0.04)",
      "theme-hero-bg": "#fffdf9",
      "theme-hero-border": "#eadccf",
      "theme-hero-shadow": "0 10px 30px rgba(111,47,29,0.05)",
      "theme-dark-panel-bg": "#6f2f1d",
      "theme-dark-panel-border": "rgba(111,47,29,0.1)",
      "theme-dark-panel-shadow": "0 18px 44px rgba(111,47,29,0.2)",
      "theme-metric-bg": "#fff7f1",
      "theme-metric-border": "#efdfd2",
      "theme-metric-shadow": "none",
      // semantic tokens
      "theme-label-text": "#7c3a20",
      "theme-hint-text": "#a0613f",
      "theme-body-text": "#6f2f1d",
      "theme-muted-text": "#c08a72",
      "theme-dialog-section-bg": "#fcf0e7",
      "theme-empty-icon-bg": "#fde8d8",
      "theme-empty-icon-text": "#f4a47c",
      "theme-input-bg": "#ffffff",
      "theme-input-border": "#d8baa7",
    },
  },
  midnight: {
    id: "midnight",
    name: "午夜主题",
    description: "深邃的深蓝暗色工作台，夜间使用护眼舒适。",
    preview: {
      shell: "linear-gradient(180deg,#0f172a 0%,#0c1424 100%)",
      surface: "#1e293b",
      accent: "#60a5fa",
      darkPanel: "#0f172a",
    },
    vars: {
      "theme-app-bg": "linear-gradient(180deg,#0f172a 0%,#0b1220 100%)",
      "theme-shell-bg": "#0f172a",
      "theme-shell-border": "#273449",
      "theme-shell-shadow": "none",
      "theme-header-bg": "#111827",
      "theme-header-border": "#273449",
      "theme-header-shadow": "0 1px 0 rgba(0,0,0,0.2)",
      "theme-sidebar-bg": "#0f172a",
      "theme-sidebar-border": "#273449",
      "theme-sidebar-text": "#94a3b8",
      "theme-sidebar-muted": "#475569",
      "theme-sidebar-hover-bg": "#172033",
      "theme-sidebar-hover-text": "#e2e8f0",
      "theme-sidebar-active-bg": "#172554",
      "theme-sidebar-active-text": "#93c5fd",
      "theme-sidebar-icon-bg": "#1e293b",
      "theme-sidebar-icon-text": "#64748b",
      "theme-sidebar-icon-active-bg": "#1e3a8a",
      "theme-sidebar-icon-active-text": "#60a5fa",
      "theme-surface-bg": "#1e293b",
      "theme-surface-border": "#334155",
      "theme-surface-shadow": "0 10px 30px rgba(2,6,23,0.28)",
      "theme-hero-bg": "#17212f",
      "theme-hero-border": "#334155",
      "theme-hero-shadow": "0 12px 32px rgba(2,6,23,0.3)",
      "theme-dark-panel-bg": "#020617",
      "theme-dark-panel-border": "rgba(2,6,23,0.12)",
      "theme-dark-panel-shadow": "0 16px 38px rgba(2,6,23,0.48)",
      "theme-metric-bg": "#162131",
      "theme-metric-border": "#314257",
      "theme-metric-shadow": "none",
      // semantic tokens
      "theme-label-text": "#cbd5e1",
      "theme-hint-text": "#64748b",
      "theme-body-text": "#f1f5f9",
      "theme-muted-text": "#64748b",
      "theme-dialog-section-bg": "#111827",
      "theme-empty-icon-bg": "#1e293b",
      "theme-empty-icon-text": "#334155",
      "theme-input-bg": "#0f172a",
      "theme-input-border": "#334155",
    },
  },
};

export const THEME_LIST = Object.values(THEMES);
